[package]
name = "ferrous-dns-jobs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ferrous-dns-application.workspace = true
ferrous-dns-domain.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
chrono.workspace = true

[dev-dependencies]
async-trait.workspace = true
chrono-tz = "0.10"
parking_lot = "0.12"
