[package]
name = "ferrous-dns-domain"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
tracing.workspace = true
toml.workspace = true
ipnetwork = { version = "0.21", features = ["serde"] }
chrono.workspace = true
chrono-tz = "0.10"
